---
core_routing:
  data:
    asn: 64512
core:
  data:
    domain: core.lab.sanderpost.nl
edge:
  data:
    domain: edge.lab.sanderpost.nl
internet:
  data:
    domain: internet.lab.sanderpost.nl
    asn: 64568
customer:
  data:
    domain: customer.lab.sanderpost.nl
...