---
R5:
  id: 0
  hostname: 172.20.20.6
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - internet
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 56
            network_type: loopback
          Gi0/0/0/0:
            area: 56
            network_type: point-to-point
          Gi0/0/0/2:
            area: 56
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r5.lab.sanderpost.nl'
        ip_address: 192.168.0.5/32
      Gi0/0/0/0:
        type: core
        host: R6
        description: 'Link: Gi0/0/0/0:r6.lab.sanderpost.nl'
        ip_address: 192.168.10.4/31
      Gi0/0/0/1:
        type: edge
        host: R100
        description: 'Edge: Gi3:r100.lab.sanderpost.nl'
        ip_address: 172.16.0.21/31
      Gi0/0/0/2:
        type: core
        host: R1
        description: 'Link: Gi0/0/0/3:r1.lab.sanderpost.nl'
        ip_address: 192.168.10.6/31
R6:
  id: 1
  hostname: 172.20.20.10
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - internet
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 56
            network_type: loopback
          Gi0/0/0/0:
            area: 56
            network_type: point-to-point
          Gi0/0/0/6:
            area: 56
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r6.lab.sanderpost.nl'
        ip_address: 192.168.0.6/32
      Gi0/0/0/0:
        type: core
        host: R5
        description: 'Link: Gi0/0/0/0:r5.lab.sanderpost.nl'
        ip_address: 192.168.10.5/31
      Gi0/0/0/1:
        type: edge
        host: R100
        description: 'Edge: Gi4:r100.lab.sanderpost.nl'
        ip_address: 172.16.0.23/31
      Gi0/0/0/6:
        type: core
        host: R2
        description: 'Link: Gi0/0/0/3:r2.lab.sanderpost.nl'
        ip_address: 192.168.10.8/31
PR1:
  id: 2
  hostname: 172.20.20.19
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - core
    - core-routing
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 0
            network_type: loopback
          GigabitEthernet2:
            area: 0
            network_type: point-to-point
          GigabitEthernet3:
            area: 0
            network_type: point-to-point
          GigabitEthernet4:
            area: 0
            network_type: point-to-point
          GigabitEthernet5:
            area: 0
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: pr1.lab.sanderpost.nl'
        ip_address: 192.168.0.10/32
      GigabitEthernet2:
        type: core
        host: R1
        description: 'Link: Gi0/0/0/1:r1.lab.sanderpost.nl'
        ip_address: 192.168.10.13/31
      GigabitEthernet3:
        type: core
        host: R2
        description: 'Link: Gi0/0/0/1:r2.lab.sanderpost.nl'
        ip_address: 192.168.10.14/31
      GigabitEthernet4:
        type: core
        host: R3
        description: 'Link: Gi0/0/0/1:r3.lab.sanderpost.nl'
        ip_address: 192.168.10.20/31
      GigabitEthernet5:
        type: core
        host: R4
        description: 'Link: Gi0/0/0/1:r4.lab.sanderpost.nl'
        ip_address: 192.168.10.22/31
  connection_options:
    netmiko:
      extras:
          conn_timeout: 1
R1:
  id: 3
  hostname: 172.20.20.15
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - edge
    - core-routing
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 0
            network_type: loopback
          Gi0/0/0/0:
            area: 0
            network_type: point-to-point
          Gi0/0/0/1:
            area: 0
            network_type: point-to-point
          Gi0/0/0/2:
            area: 0
            network_type: point-to-point
          Gi0/0/0/3:
            area: 56
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r1.lab.sanderpost.nl'
        ip_address: 192.168.0.1/32
      Gi0/0/0/0:
        type: core
        host: R2
        description: 'Link: Gi0/0/0/0:r2.lab.sanderpost.nl'
        ip_address: 192.168.10.10/31
      Gi0/0/0/1:
        type: core
        host: pr1
        description: 'Link: Gi1:pr1.lab.sanderpost.nl'
        ip_address: 192.168.10.12/31
      Gi0/0/0/2:
        type: core
        host: r3
        description: 'Link: Gi0/0/0/2:r3.lab.sanderpost.nl'
        ip_address: 192.168.10.16/31
      Gi0/0/0/3:
        type: core
        host: r5
        description: 'Link: Gi0/0/0/2:r5.lab.sanderpost.nl'
        ip_address: 192.168.10.7/31
      Gi0/0/0/4:
        type: edge
        host: CE1
        description: 'Edge: Gi3:ce1.lab.sanderpost.nl'
        ip_address: 172.16.0.0/31
      Gi0/0/0/5:
        type: edge
        host: CE2
        description: 'Edge: Gi3:ce2.lab.sanderpost.nl'
        ip_address: 172.16.0.5/31
R2:
  id: 4
  hostname: 172.20.20.9
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - edge
    - core-routing
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 0
            network_type: loopback
          Gi0/0/0/0:
            area: 0
            network_type: point-to-point
          Gi0/0/0/1:
            area: 0
            network_type: point-to-point
          Gi0/0/0/2:
            area: 0
            network_type: point-to-point
          Gi0/0/0/3:
            area: 56
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r2.lab.sanderpost.nl'
        ip_address: 192.168.0.2/32
      Gi0/0/0/0:
        type: core
        host: r1
        description: 'Link: Gi0/0/0/0:r1.lab.sanderpost.nl'
        ip_address: 192.168.10.11/31
      Gi0/0/0/1:
        type: core
        host: pr1
        description: 'Link: Gi3.pr1.lab.sanderpost.nl'
        ip_address: 192.168.10.15/31
      Gi0/0/0/2:
        type: core
        host: r4
        description: 'Link: Gi0/0/0/2:r4.lab.sanderpost.nl'
        ip_address: 192.168.10.18/31
      Gi0/0/0/3:
        type: core
        host: r6
        description: 'Link: Gi0/0/0/2:r6.lab.sanderpost.nl'
        ip_address: 192.168.10.9/31
      Gi0/0/0/4:
        type: edge
        host: CE4
        description: 'Edge: Gi3:ce4.lab.sanderpost.nl'
        ip_address: 172.16.0.2/31
R3:
  id: 5
  hostname: 172.20.20.14
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - edge
    - core-routing
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 0
            network_type: loopback
          Gi0/0/0/0:
            area: 0
            network_type: point-to-point
          Gi0/0/0/1:
            area: 0
            network_type: point-to-point
          Gi0/0/0/2:
            area: 0
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r3.lab.sanderpost.nl'
        ip_address: 192.168.0.3/32
      Gi0/0/0/0:
        type: core
        host: r4
        description: 'Link: Gi0/0/0/0:r4.lab.sanderpost.nl'
        ip_address: 192.168.10.24/31
      Gi0/0/0/1:
        type: core
        host: pr1
        description: 'Link: Gi4:pr1.lab.sanderpost.nl'
        ip_address: 192.168.10.21/31
      Gi0/0/0/2:
        type: core
        host: r1
        description: 'Link: Gi0/0/0/2:r1.lab.sanderpost.nl'
        ip_address: 192.168.10.17/31
      Gi0/0/0/3:
        type: edge
        host: CE3
        description: 'Edge: Gi3:ce3.lab.sanderpost.nl'
        ip_address: 172.16.0.9/31
      Gi0/0/0/4:
        type: edge
        host: CE4
        description: 'Edge: Gi4:ce2.lab.sanderpost.nl'
        ip_address: 172.16.0.7/31
R4:
  hostname: 172.20.20.16
  port: 22
  username: clab
  password: clab@123
  platform: iosxr
  groups:
    - edge
    - core-routing
  data:
    routing:
      ospf:
        interfaces:
          Loopback0:
            area: 0
            network_type: loopback
          Gi0/0/0/0:
            area: 0
            network_type: point-to-point
          Gi0/0/0/1:
            area: 0
            network_type: point-to-point
          Gi0/0/0/2:
            area: 0
            network_type: point-to-point
    interfaces:
      Loopback0:
        type: loopback
        description: 'Loopback: r4.lab.sanderpost.nl'
        ip_address: 192.168.0.4/32
      Gi0/0/0/0:
        type: core
        host: r3
        description: 'Link: Gi0/0/0/0:r3.lab.sanderpost.nl'
        ip_address: 192.168.10.25/31
      Gi0/0/0/1:
        type: core
        host: pr1
        description: 'Link: Gi5:pr1.lab.sanderpost.nl'
        ip_address: 192.168.10.23/31
      Gi0/0/0/2:
        type: core
        host: r2
        description: 'Link: Gi0/0/0/2:r2.lab.sanderpost.nl'
        ip_address: 192.168.10.19/31
      Gi0/0/0/3:
        type: edge
        host: CE5
        description: 'Edge: Gi3:ce5.lab.sanderpost.nl'
        ip_address: 172.16.0.10/31
R100:
  hostname: 172.20.20.100
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: inside
        host: E1
        description: 'Inside: Eth1:e1.lab.sanderpost.nl'
        ip_address: 10.100.0.1/24
      GigabitEthernet3:
        type: outside
        host: R5
        description: 'Outside: Gi0/0/0/1:r5.lab.sanderpost.nl'
        ip_address: 172.16.0.20/31
      GigabitEthernet4:
        type: outside
        host: R6
        description: 'Outside Gi0/0/0/1:r6.lab.sanderpost.nl'
        ip_address: 172.16.0.22/31
CE1:
  hostname: 172.20.20.101
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: inside
        host: C1
        description: 'Inside Eth1:c1.lab.sanderpost.nl' 
        ip_address: 10.1.0.1/24
      GigabitEthernet3:
        type: outside
        host: R1
        description: 'Outside: Gi0/0/0/4:r1.lab.sanderpost.nl'
        ip_address: 172.16.0.1/31
CE2:
  hostname: 172.20.20.102
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: inside
        host: C2
        description: 'Inside: Eth1:c2.lab.sanderpost.nl' 
        ip_address: 10.2.0.1/24
      GigabitEthernet3:
        type: outside
        host: R1
        description: 'Outside: Gi0/0/0/5:r1.lab.sanderpost.nl'
        ip_address: 172.16.0.4/31
      GigabitEthernet4:
        type: outside
        host: R3
        description: 'Outside: r3.Gi0/0/0/4.lab.sanderpost.nl'
        ip_address: 172.16.0.6/31
CE3:
  hostname: 172.20.20.103
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: inside
        host: C3
        description: 'Inside: Eth1:c3.lab.sanderpost.nl' 
        ip_address: 10.3.0.1/24
      GigabitEthernet3:
        type: outside
        host: R3
        description: 'Outside: Gi0/0/0/3:r3.lab.sanderpost.nl'
        ip_address: 172.16.0.8/31
CE4:
  hostname: 172.20.20.104
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: outside
        host: C4
        description: 'Inside: Eth1.c4.lab.sanderpost.nl' 
        ip_address: 10.4.0.1/24
      GigabitEthernet3:
        type: inside
        host: R2
        description: 'Outside: Gi0/0/0/4:r2.lab.sanderpost.nl'
        ip_address: 172.16.0.3/31
CE5:
  hostname: 172.20.20.105
  port: 22
  username: admin
  password: admin
  platform: ios
  groups:
    - customer
  data:
    interfaces:
      GigabitEthernet2:
        type: outside
        host: C5
        description: 'Inside: Eth1.c5.lab.sanderpost.nl'
        ip_address: 10.5.0.1/24
      GigabitEthernet3:
        type: inside
        host: R4
        description: 'Outside: Gi0/0/0/3.r4.lab.sanderpost.nl'
        ip_address: 172.16.0.11/31
...