---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "automation/nornir/inventory/hosts.yaml"
    group_file: "automation/nornir/inventory/groups.yaml"
    defaults_file: "automation/nornir/inventory/defaults.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 100
...